# 0. Import Numpy

In [1]:
import numpy as np

In [3]:
np.__version__

'1.13.3'

**Initialize using python list:**

In [4]:
a = np.array([1,2,3]) 

In [5]:
print(a)

[1 2 3]


In [6]:
b = np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


**Initialize using some NumPy functions:    **

In [7]:
c = np.zeros((2,3))
print(c)

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [8]:
d = np.ones((3,4))
print(d)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [9]:
e = np.arange(2,10,2)
print(e)

[2 4 6 8]


In [10]:
f = np.linspace(0,100,6)
print(f)

[   0.   20.   40.   60.   80.  100.]


In [11]:
g = np.full((2,3), 6)
print(g)

[[6 6 6]
 [6 6 6]]


In [12]:
h = np.eye(3)
print(h)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [13]:
i = np.eye(3,4)
print(i)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]]


**Random Initialization:**

In [14]:
j = np.random.rand(4,5) # samples from a uniform distribution over [0, 1)
print(j)

[[ 0.1939669   0.57282709  0.09668092  0.84906063  0.8932963 ]
 [ 0.96713084  0.6441912   0.73141142  0.29534866  0.2336527 ]
 [ 0.83261866  0.03447211  0.5875303   0.84546013  0.21221535]
 [ 0.22429305  0.26107056  0.454702    0.71888373  0.4420792 ]]


In [15]:
k = np.random.randint(2,5,size = (2,3))#samples from discrete uniform distribution in the specified half-open interval
print(k)

[[2 4 3]
 [3 3 4]]


In [16]:
mu, sigma = 0, 0.1 # mean and standard deviation
l = np.random.normal(mu, sigma, (3, 4)) # samples from the "standard normal" distribution
print(l)

[[-0.17535169  0.26198817 -0.06656258 -0.04302989]
 [-0.14636025 -0.03607307  0.00300744 -0.13143317]
 [ 0.14604419  0.02977634  0.00292227 -0.14542604]]


In [17]:
m = np.random.randn(2, 4) # samples from the "standard normal" distribution
print(m)

[[-0.28797526  1.27113731  0.34174226 -0.42069685]
 [ 1.55697445 -0.68535872 -2.92454405  1.64648691]]


See the list of other distributions in: https://docs.scipy.org/doc/numpy-1.10.1/reference/routines.random.html

# 2. Inspecting Properties:

In [18]:
a = np.random.randint(0,10, (2,3,4))
print(a)

[[[1 9 2 0]
  [5 9 1 9]
  [1 2 6 4]]

 [[2 6 2 0]
  [1 5 7 3]
  [5 6 9 0]]]


In [19]:
a.size

24

In [20]:
a.shape

(2, 3, 4)

In [21]:
a.dtype

dtype('int32')

In [22]:
b = np.array([1.0, 2.0])
b.dtype

dtype('float64')

In [23]:
b_int = b.astype(int)
print(b_int)

[1 2]


In [24]:
a_list = a.tolist()
print(a_list)

[[[1, 9, 2, 0], [5, 9, 1, 9], [1, 2, 6, 4]], [[2, 6, 2, 0], [1, 5, 7, 3], [5, 6, 9, 0]]]


In [25]:
print(np.asarray(a_list))

[[[1 9 2 0]
  [5 9 1 9]
  [1 2 6 4]]

 [[2 6 2 0]
  [1 5 7 3]
  [5 6 9 0]]]


In [26]:
np.info(np.random)

Random Number Generation

==================== =========================================================
Utility functions
random_sample        Uniformly distributed floats over ``[0, 1)``.
random               Alias for `random_sample`.
bytes                Uniformly distributed random bytes.
random_integers      Uniformly distributed integers in a given range.
permutation          Randomly permute a sequence / generate a random sequence.
shuffle              Randomly permute a sequence in place.
seed                 Seed the random number generator.
choice               Random sample from 1-D array.

==================== =========================================================

==================== =========================================================
Compatibility functions
rand                 Uniformly distributed values.
randn                Normally distributed values.
ranf                 Uniformly distributed floating point numbers.
randint              Uniformly distribu

# 3. Indexing/Slicing/Subsetting

In [27]:
a = np.random.randint(0,10, (2,3,4))
print(a)

[[[0 1 9 6]
  [4 0 5 3]
  [5 3 6 2]]

 [[2 6 6 3]
  [0 7 1 1]
  [8 9 8 1]]]


In [28]:
a[0,0,0]

0

In [29]:
a[0][0][0]

0

In [30]:
a[1,0,3]

3

In [31]:
a[1,1]


array([0, 7, 1, 1])

In [32]:
a[:,:,3]


array([[6, 3, 2],
       [3, 1, 1]])

In [33]:
a[:,0:2,3]


array([[6, 3],
       [3, 1]])

In [34]:
a[:,:2,3]


array([[6, 3],
       [3, 1]])

In [35]:
a[:,:2,-1]


array([[6, 3],
       [3, 1]])

In [36]:
a[:,:2,-2]


array([[9, 5],
       [6, 1]])

In [37]:
a

array([[[0, 1, 9, 6],
        [4, 0, 5, 3],
        [5, 3, 6, 2]],

       [[2, 6, 6, 3],
        [0, 7, 1, 1],
        [8, 9, 8, 1]]])

In [38]:
print(a<5)


[[[ True  True False False]
  [ True  True False  True]
  [False  True False  True]]

 [[ True False False  True]
  [ True False  True  True]
  [False False False  True]]]


In [43]:
print(a<5)

[[[ True  True False False]
  [ True  True False  True]
  [False  True False  True]]

 [[ True False False  True]
  [ True False  True  True]
  [False False False  True]]]


In [44]:
print(a[a<5])

[0 1 4 0 3 3 2 2 3 0 1 1 1]


In [46]:
a[:,:2,3] = np.zeros((2,2))
a

array([[[0, 1, 9, 0],
        [4, 0, 5, 0],
        [5, 3, 6, 2]],

       [[2, 6, 6, 0],
        [0, 7, 1, 0],
        [8, 9, 8, 1]]])

# 4. Copying/Sorting/Reshaping

In [47]:
a = np.array([1,2,3])
b = a
b[0] = 0
a[0] == b[0]

True

In [48]:
c = np.copy(a)
c[0] = 5
a[0] == c[0]

False

In [49]:
a = np.random.randint(0,10, (3,4))
print(a)

[[3 8 2 0]
 [0 5 3 2]
 [6 6 3 6]]


In [50]:
b = np.sort(a) # sort along the last axis
print(b)

[[0 2 3 8]
 [0 2 3 5]
 [3 6 6 6]]


In [51]:
np.sort(a, axis=0)

array([[0, 5, 2, 0],
       [3, 6, 3, 2],
       [6, 8, 3, 6]])

In [52]:
c = a.T
print(c)

[[3 0 6]
 [8 5 6]
 [2 3 3]
 [0 2 6]]


In [53]:
d = a.reshape(2,6)
print(d)

[[3 8 2 0 0 5]
 [3 2 6 6 3 6]]


In [54]:
e = a.flatten()
print(e)

[3 8 2 0 0 5 3 2 6 6 3 6]


In [55]:
print(a)

[[3 8 2 0]
 [0 5 3 2]
 [6 6 3 6]]


# 5. Adding/Removing/Combining/Spliting

In [56]:
a = np.arange(5)
b = np.arange(5,10)
print(a,b)

[0 1 2 3 4] [5 6 7 8 9]


In [57]:
c = np.vstack([a,b])
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [58]:
print(np.hstack([a,b]))

[0 1 2 3 4 5 6 7 8 9]


In [59]:
np.delete(c,1,1)

array([[0, 2, 3, 4],
       [5, 7, 8, 9]])

In [60]:
np.delete(c,1,0)

array([[0, 1, 2, 3, 4]])

In [61]:
print(np.split(c,2))

[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]])]


See more in: https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.array-manipulation.html

# 6. Math

## 6.1 Elementwise

In [62]:
a = np.arange(0,10).reshape(2,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [63]:
b = np.random.randint(1,10,(2,5))
print(b)

[[4 3 2 8 4]
 [2 4 8 6 4]]


In [64]:
c = np.add(a, 1)
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [65]:
c = a + 1
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [66]:
d = a - b # np.subtract(a,b)
print(d)

[[-4 -2  0 -5  0]
 [ 3  2 -1  2  5]]


In [67]:
e = a * b #np.multiply(a,b)
print(e)

[[ 0  3  4 24 16]
 [10 24 56 48 36]]


In [68]:
f = a/b # np.divide(a,b)
print(f)

[[ 0.          0.33333333  1.          0.375       1.        ]
 [ 2.5         1.5         0.875       1.33333333  2.25      ]]


In [69]:
g = a**b # np.power(a,b)
print(g)

[[      0       1       4    6561     256]
 [     25    1296 5764801  262144    6561]]


In [70]:
h = np.sqrt(a)
print(h)

[[ 0.          1.          1.41421356  1.73205081  2.        ]
 [ 2.23606798  2.44948974  2.64575131  2.82842712  3.        ]]


In [71]:
i = np.sin(a)
print(i)

[[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155   0.6569866   0.98935825  0.41211849]]


For more mathematical functions of NumPy visit: https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html

## 6.2 Matrix operations

In [72]:
a = np.array([[1, 0],[1, 1], [0, 1]])
print(a)

[[1 0]
 [1 1]
 [0 1]]


In [73]:
b = np.array([[0, -1], [1, 1]])
print(b)

[[ 0 -1]
 [ 1  1]]


Adding and subtracting is the same as prior section.

In [74]:
np.matmul(a,b)

array([[ 0, -1],
       [ 1,  0],
       [ 1,  1]])

In [75]:
np.linalg.inv(b)

array([[ 1.,  1.],
       [-1., -0.]])

In [76]:
np.linalg.det(b)

1.0

In [77]:
np.trace(b)

1

For more information about linear algebra in NumPy see: https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.linalg.html

## 7. Statistics

In [79]:
mu, sigma = 0, 0.1 # mean and standard deviation
a = np.random.normal(mu, sigma, 1000)
b = 3*a+1

In [80]:
np.mean(a)

-0.00021279520155163478

In [81]:
np.median(a)

-0.0012012004534761814

In [82]:
np.std(a)

0.10003327965798414

In [83]:
np.var(a)

0.010006657039132463

In [84]:
np.cov(np.vstack([a,b])) # compute the covariance matrix of two random variable a and b 

array([[ 0.01001667,  0.03005002],
       [ 0.03005002,  0.09015006]])

In [85]:
c = np.array([[1,2],[3,4]])
c

array([[1, 2],
       [3, 4]])

In [86]:
np.sum(c)

10

In [87]:
np.sum(c, axis=1)

array([3, 7])

For more statistics in NumPy see: https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.statistics.html

## 8. Import/Export
save and load NumPy array in disk:

In [91]:
np.save('numpy_files/123', np.array([[1, 2, 3], [4, 5, 6]]))

In [92]:
np.load('numpy_files/123.npy')

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
a=np.array([[1, 2, 3], [4, 5, 6]])
b=np.array([1, 2])
np.savez('numpy_files/123.npz', a=a, b=b)
data = np.load('numpy_files/123.npz')
print(data['a'])
print(data['b'])
data.close()

[[1 2 3]
 [4 5 6]]
[1 2]


For more I/O routines: https://docs.scipy.org/doc/numpy/reference/routines.io.html

Learn more about NumPy: https://docs.scipy.org/doc/numpy/reference/routines.html